# Generated by Django 5.1.2 on 2024-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='passenger',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='passenger', to='flights.flight'),
        ),
    ]
